### ISSUE TITLE
Add professor department while searching

### ISSUE THREAD

**Issue by kaustubhhiware** [metakgp/mcmp#14]
A friend of mine suggested we also show the department of the professor when displaying search results. 

This is helpful if a student wants to work within their department only.

Current search result:   `Sourangshu Bhattacharya | Machine Learning`

Suggested change:    `Sourangshu Bhattacharya | CS | Machine Learning`

I can take this up if the need for this is acknowledged by other folks.

**Comment by athityakumar** [comment]
Makes sense, given that MCMP is usually used to for deciding on BTP/MTP. Also, would some kind of filter (multi-select dropdown) for department be a useful feature?

For example, if someone searches specifically for CS - search results like `CS Kumar | ME | Robotics` would still appear. This could be handled better by a filter button. But again, these may not be highly occurring results - so, we can skip the filter feature if it's too much work for little enhancement in result.

**Comment by icyflame** [comment]
The current JSON file doesn't have this data. We will have the scrape the data again with this data. Not sure what script was originally used to scrape this data. Definitely a good idea.

**Comment by icyflame** [comment]
Okay, found all the required details here. Figuring out how this works. Will create a patch if it's not too involved.

**Comment by athityakumar** [comment]
Fixed by #16 - not sure why this issue hasn't been closed automatically upon merging #16 🤔
