### ISSUE TITLE
Integrate with wimp

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mcmp#17]
Add hyperlink of the search results to the corresponding page in WIMP. Related to https://github.com/themousepotato/wimp/issues/8

**Comment by icyflame** [comment]
@themousepotato One way to do this is implemented in [mfqp](https://github.com/metakgp/mfqp). I use the search string to pre-fill the text field. Then, I trigger the functions that generate the results. This is the [PR](https://github.com/metakgp/mfqp/pull/30) if you want to take a look. These two projects work together very well.

**Comment by themousepotato** [comment]
This issue is fixed, no? cc @athityakumar @icyflame

**Comment by thealphadollar** [comment]
@icyflame Please close this.

**Comment by thealphadollar** [comment]
Fixed in #18
