### ISSUE TITLE
Prettify UI

### ISSUE THREAD

**Issue by raivivek** [metakgp/mcmp#7]
@icyflame You may wish to work on this. Once the UI is revamped a bit, we can launch/relaunch this.

**Comment by icyflame** [comment]
@vivekiitkgp Yeah, probably. Are we planning to have the same simple single text field layout as mfqp?

**Comment by icyflame** [comment]
@vivekiitkgp Anything else on the front page? (I feel like the present minimalistic interface is good enough.)

**Comment by raivivek** [comment]
The same simple single text field layout is good enough. But may be we can
present the results in a better way?

Like may be, something more than just a link to other place.

## 

https://vivekiitkgp.github.io

**Comment by raivivek** [comment]
But again, this is just personal feeling. If we want mcmp to simply index
and search results quickly, then we have already solved the problem.

## 

https://vivekiitkgp.github.io

**Comment by athityakumar** [comment]
I think we can make the UI of `mcmp` same as `mfqp`? Please have a look at [this](https://github.com/metakgp/mfqp/issues/20) discussion , @vivekiitkgp and @icyflame.

**Comment by raivivek** [comment]
I feel this is resolved to my satisfaction. If more changes are needed, feel free to open an issue with the desired request. :-)
