### ISSUE TITLE
Remove duplicate results

### ISSUE THREAD

**Issue by OrkoHunter** [metakgp/mcmp#8]
Few searches display duplicate professor names. If it's possible then they should be removed, if not then please close the issue.

**Comment by athityakumar** [comment]
@icyflame : We could use the 'json' gem to read from the prof_details.json as objects, club all projects under a single prof into "fields" field like "Cryptography , Artificial Intelligence , ..." & overwrite the objects into the prof_details.json right?

**Comment by icyflame** [comment]
@OrkoHunter Can you suggest some examples of searches that throw duplicate results?

**Comment by icyflame** [comment]
![screen shot 2016-06-13 at 7 25 13 pm](https://cloud.githubusercontent.com/assets/3668034/16009968/a26d416c-319c-11e6-8deb-5d3f84befab8.png)

@OrkoHunter Do you mean things like this? This seems to be a simple case of duplication in the JSON itself. 

I don't think that duplicates of professors, but with different research areas is undesirable. If anything, I believe it is desirable to have that. (cc @xtinct @amrav)

@athityakumar What you said might be the way to go. It seems like that JSON file hasn't been cleaned up yet.

**Comment by raivivek** [comment]
I think that having same professor name corresponding to different research areas isn't really a bad idea. But look at the second and third result in the image you have posted. That's something we'd like to omit.

**Comment by athityakumar** [comment]
@icyflame @vivekiitkgp : What about the 4 "C Retna Raj" options? Should such entries be changed to a single "C Retna Raj | Optical and electrochemical sensors , Electrocatalysis and fuel cell , Energy conversion and storage devices , Inorganic multifunctional nanomaterials"? Or should leave them as it is?

**Comment by raivivek** [comment]
I guess it's okay if we leave them. Atomic entries ;)

**Comment by athityakumar** [comment]
Pushed codes to fix this issue. :smile: 

makelists.py file doesn't take anymore duplicated content.
remove-duplicates.rb file can be used to remove all existing duplicates.

**Comment by icyflame** [comment]
Interesting choice of languages for those scripts, @athityakumar 👍

**Comment by athityakumar** [comment]
@icyflame : Sarcasm? :wink: 

P.S - For some reason , github provides collaborators the power of editing the comments of other collaborators too in issue discussions... All hail, github! :laughing:

**Comment by athityakumar** [comment]
@icyflame @vivekiitkgp @OrkoHunter : If we're leaving the "C Retna Raj"-like results as it is, can we close this issue? :smile:

**Comment by icyflame** [comment]
![screen shot 2016-06-14 at 12 02 30 pm](https://cloud.githubusercontent.com/assets/3668034/16033122/e8abf598-3227-11e6-8569-d4dd52f6e922.png)

@athityakumar Congratulations! Those `C Retna Raj` duplicates are gone!
